language: clojure
env:
    - TEST_DIR=dumb-clojure-app
    - TEST_DIR=dumb-python-app
before_install:
    - npm install gulp
    - sudo apt-get update
    - sudo apt-get install leiningen
script: cd $TEST_DIR && npm install && npm test
